export const GET_NAME = 'GET_NAME';
export const GET_MOST_POPULAR = 'GET_MOST_POPULAR';
export const FETCH_MOST_POPULAR = 'FETCH_MOST_POPULAR';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_MOVIE = 'GET_MOVIE';
export const EMPTY_SEARCH_RESULTS = 'EMPTY_SEARCH_RESULTS';
